export const STRIPE_CUSTOMER = {
  NOT_EXISTENT: 'CUSTOMER_NOT_EXIST',
  NO_ACTIVE_SUBSCRIPTION: 'CUSTOMER_HAS_NO_ACTIVE_SUBSCRIPTION',
  WITH_ACTIVE_SUBSCRIPTION: 'CUSTOMER_WITH_ACTIVE_SUBSCRIPTION'
};

export const STRIPE_LOOKUP_KEYS = {
  EDDY_FREE_MONTHLY: 'EDDY_FREE_MONTHLY',
  EDDY_FREE_YEARLY: 'EDDY_FREE_YEARLY',
  EDDY_PRO_MONTHLY: 'EDDY_PRO_MONTHLY',
  EDDY_PRO_YEARLY: 'EDDY_PRO_YEARLY',
  EDDY_MAX_MONTHLY: 'EDDY_MAX_MONTHLY',
  EDDY_MAX_YEARLY: 'EDDY_MAX_YEARLY',
};
