export const STRIPE_CUSTOMER = {
  NOT_EXISTENT: 'CUSTOMER_NOT_EXIST',
  NO_ACTIVE_SUBSCRIPTION: 'CUSTOMER_HAS_NO_ACTIVE_SUBSCRIPTION',
  WITH_ACTIVE_SUBSCRIPTION: 'CUSTOMER_WITH_ACTIVE_SUBSCRIPTION'
};
