export enum STRIPE_SUBSCRIPTION_LOOKUP_KEY {
  EDDY_FREE_MONTHLY = 'EDDY_FREE_MONTHLY',
  EDDY_FREE_YEARLY = 'EDDY_FREE_YEARLY',
  EDDY_PRO_MONTHLY = 'EDDY_PRO_MONTHLY',
  EDDY_PRO_YEARLY = 'EDDY_PRO_YEARLY',
  EDDY_MAX_MONTHLY = 'EDDY_MAX_MONTHLY',
  EDDY_MAX_YEARLY = 'EDDY_MAX_YEARLY',
}
